name: CI

on:
  push:
    branches: 
      - master
    tags : 
      - '*'

jobs:
  build:
    runs-on: macOS-latest  

    steps:
      - uses: actions/checkout@v3
      - name: Publish to Cocoapod
        env: 
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push AdBrixRmKitQA.podspec
